using System.Text.Json;
using System.Text.Json.Nodes;
using System.Text.RegularExpressions;
using OpenXLR.Core;
using OpenXLR.UI.Skinning;

namespace OpenXLR.Tests;

[Collection("xdg-config")]
public sealed class OmarchyPluginTests
{
    [Fact]
    public void TheOmarchyMeterTableMatchesTheEmbeddedSkins()
    {
        JsonObject palettes = new();
        (string Key, string Token)[] fields =
        [
            ("fill", "Fill"), ("warning", "Warning"), ("hot", "Hot"),
            ("track", "Track"), ("warningLevel", "WarningLevel"), ("hotLevel", "HotLevel")
        ];
        string skins = Path.Combine(Root(), "src", "OpenXLR.UI", "Assets", "Skins");
        foreach (string directory in Directory.GetDirectories(skins).Order(StringComparer.Ordinal))
        {
            using JsonDocument document = JsonDocument.Parse(File.ReadAllText(Path.Combine(directory, "skin.json")));
            JsonElement tokens = document.RootElement.GetProperty("tokens");
            JsonObject palette = new();
            foreach ((string key, string token) in fields)
            {
                string name = "Ox.Meter." + token;
                if (tokens.TryGetProperty(name, out JsonElement value))
                    palette[key] = JsonNode.Parse(value.GetRawText());
                else
                    palette[key] = Assert.IsType<double>(SkinTokens.Find(name)!.Default);
            }
            palettes[Path.GetFileName(directory)] = palette;
        }
        Assert.NotEmpty(palettes);
        string generated = "// Generated by tools/omarchy-skins.py. Do not edit.\nvar palettes = " +
            palettes.ToJsonString(new JsonSerializerOptions { WriteIndented = true }) + ";\n";
        Assert.Equal(generated, File.ReadAllText(Path.Combine(Root(), "packaging", "omarchy", "openxlr.mixer", "Skins.js")));
    }

    [Fact]
    public void TheShippedPluginMeetsOmarchysManifestRules()
    {
        string plugin = Path.Combine(Root(), "packaging", "omarchy", "openxlr.mixer");
        using JsonDocument document = JsonDocument.Parse(File.ReadAllText(Path.Combine(plugin, "manifest.json")));
        JsonElement manifest = document.RootElement;
        // Keep this table and the path checks with bin/omarchy-plugin-validate
        // from Omarchy quattro. Unknown kinds have no guessed entry point.
        Assert.Equal(JsonValueKind.Number, manifest.GetProperty("schemaVersion").ValueKind);
        Assert.Equal(1, manifest.GetProperty("schemaVersion").GetDouble());
        foreach (string field in new[] { "id", "name", "version", "kinds", "entryPoints" })
            Assert.True(manifest.TryGetProperty(field, out _), $"missing {field}");
        string id = Assert.IsType<string>(manifest.GetProperty("id").GetString());
        Assert.Matches(new Regex(@"^[A-Za-z0-9][A-Za-z0-9._-]*$", RegexOptions.CultureInvariant), id);
        Assert.DoesNotContain("..", id, StringComparison.Ordinal);
        Assert.False(id.StartsWith("omarchy.", StringComparison.Ordinal));
        Assert.Equal(Path.GetFileName(plugin), id);
        Assert.False(string.IsNullOrWhiteSpace(manifest.GetProperty("name").GetString()));
        Assert.False(string.IsNullOrWhiteSpace(manifest.GetProperty("version").GetString()));

        JsonElement kinds = manifest.GetProperty("kinds");
        Assert.Equal(JsonValueKind.Array, kinds.ValueKind);
        Assert.NotEmpty(kinds.EnumerateArray());
        JsonElement entries = manifest.GetProperty("entryPoints");
        Assert.Equal(JsonValueKind.Object, entries.ValueKind);
        Dictionary<string, string> required = new()
        {
            ["bar"] = "bar", ["bar-widget"] = "barWidget", ["menu"] = "menu",
            ["overlay"] = "overlay", ["panel"] = "panel", ["service"] = "service"
        };
        foreach (JsonElement kind in kinds.EnumerateArray())
            if (required.TryGetValue(kind.GetString()!, out string? entry))
                Assert.True(entries.TryGetProperty(entry, out _), $"{kind} needs entryPoints.{entry}");
        foreach (JsonProperty entry in entries.EnumerateObject())
        {
            string path = Assert.IsType<string>(entry.Value.GetString());
            Assert.NotEmpty(path);
            Assert.DoesNotContain('\n', path);
            Assert.DoesNotContain("..", path, StringComparison.Ordinal);
            Assert.False(Path.IsPathRooted(path));
            Assert.True(File.Exists(Path.Combine(plugin, path)), $"missing entry point {path}");
        }
        if (manifest.TryGetProperty("barWidget", out JsonElement widget) &&
            widget.TryGetProperty("defaultSection", out JsonElement section))
            Assert.Contains(section.GetString(), new[] { "left", "center", "right" });
        NoLinks(new DirectoryInfo(plugin));
    }

    private static void NoLinks(DirectoryInfo directory)
    {
        foreach (FileSystemInfo entry in directory.EnumerateFileSystemInfos())
        {
            if (entry.Name == ".git") continue;
            Assert.Null(entry.LinkTarget);
            if (entry is DirectoryInfo child) NoLinks(child);
        }
    }

    [Fact]
    public async Task EnablingLinksThePackageAndLetsOmarchyOwnTheConfiguration()
    {
        if (!OperatingSystem.IsLinux()) return;
        using EnableFixture fixture = new();
        ProcessResult result = await fixture.Run();
        Assert.True(result.Ok, result.Stderr);
        Assert.Equal(fixture.Plugin, new DirectoryInfo(fixture.Destination).LinkTarget);
        Assert.Equal(new[] { "shell ping", "plugin validate " + fixture.Plugin,
            "shell rescanPlugins", "plugin enable openxlr.mixer" }, File.ReadAllLines(fixture.Log));
        File.Delete(fixture.Log);
        Assert.True((await fixture.Run()).Ok);
        Assert.Equal(fixture.Plugin, new DirectoryInfo(fixture.Destination).LinkTarget);
        Assert.False(File.Exists(Path.Combine(fixture.Home, ".config", "omarchy", "shell.json")));
    }

    [Theory]
    [InlineData(false)]
    [InlineData(true)]
    public async Task EnablingDoesNotReplaceAnExistingPlugin(bool symlink)
    {
        if (!OperatingSystem.IsLinux()) return;
        using EnableFixture fixture = new();
        Directory.CreateDirectory(Path.GetDirectoryName(fixture.Destination)!);
        if (symlink) Directory.CreateSymbolicLink(fixture.Destination, fixture.Home);
        else Directory.CreateDirectory(fixture.Destination);
        ProcessResult result = await fixture.Run();
        Assert.False(result.Ok);
        Assert.Contains("already", result.Stderr, StringComparison.Ordinal);
        Assert.DoesNotContain("shell rescanPlugins", File.ReadAllLines(fixture.Log));
        Assert.Equal(symlink ? fixture.Home : null, new DirectoryInfo(fixture.Destination).LinkTarget);
    }

    [Theory]
    [InlineData("ping")]
    [InlineData("validate")]
    public async Task EnablingStopsBeforeLinkingWhenTheSessionOrPluginIsInvalid(string failure)
    {
        if (!OperatingSystem.IsLinux()) return;
        using EnableFixture fixture = new();
        ProcessResult result = await fixture.Run(failure);
        Assert.False(result.Ok);
        Assert.False(Directory.Exists(fixture.Destination));
        Assert.DoesNotContain("shell rescanPlugins", File.ReadAllLines(fixture.Log));
    }

    /// <summary>
    /// The enable command reads the plugin's id itself, so it refuses a
    /// directory that holds a different plugin. It reads the manifest without
    /// jq, which the RPM build container does not have and a user's machine
    /// is not required to have either.
    /// </summary>
    [Fact]
    public async Task EnablingRefusesAPluginDirectoryWithAnotherId()
    {
        if (!OperatingSystem.IsLinux()) return;
        using EnableFixture fixture = new();
        string other = Path.Combine(fixture.Home, "other.plugin");
        Directory.CreateDirectory(other);
        await File.WriteAllTextAsync(Path.Combine(other, "manifest.json"), @"{ ""schemaVersion"": 1, ""id"": ""other.plugin"" }");
        ProcessResult result = await fixture.Run(plugin: other);
        Assert.False(result.Ok);
        Assert.Contains("expected openxlr.mixer", result.Stderr, StringComparison.Ordinal);
        Assert.False(Directory.Exists(fixture.Destination));
        Assert.DoesNotContain("shell rescanPlugins", File.ReadAllLines(fixture.Log));
    }

    private sealed class EnableFixture : IDisposable
    {
        private readonly string _directory = Path.Combine(Path.GetTempPath(), "openxlr-omarchy-" + Guid.NewGuid());
        public string Home => Path.Combine(_directory, "user home");
        public string Plugin => Path.Combine(Root(), "packaging", "omarchy", "openxlr.mixer");
        public string Destination => Path.Combine(Home, ".config", "omarchy", "plugins", "openxlr.mixer");
        public string Log => Path.Combine(_directory, "calls");

        public EnableFixture()
        {
            Directory.CreateDirectory(Home);
            foreach (string executable in new[] { "omarchy", "omarchy-shell" })
                ExecutableScript.Write(Path.Combine(_directory, executable), """
                    printf '%s\n' "$*" >> "$OPENXLR_TEST_CALLS"
                    if [ "$*" = 'shell ping' ]; then
                        [ "$OPENXLR_TEST_FAILURE" != ping ] || exit 1
                        printf 'ok\n'
                    fi
                    if [ "$1 $2" = 'plugin validate' ]; then
                        [ "$OPENXLR_TEST_FAILURE" != validate ] || exit 1
                    fi
                    """);
        }

        public Task<ProcessResult> Run(string failure = "", string? plugin = null) => ProcessRunner.RunAsync("bash",
            [Path.Combine(Root(), "packaging", "omarchy", "openxlr-omarchy-enable"), plugin ?? Plugin],
            environment: new Dictionary<string, string>
            {
                ["HOME"] = Home,
                ["XDG_CONFIG_HOME"] = Path.Combine(_directory, "different-config"),
                ["PATH"] = _directory + ":/usr/bin:/bin",
                ["OPENXLR_TEST_CALLS"] = Log,
                ["OPENXLR_TEST_FAILURE"] = failure
            });

        public void Dispose() => Directory.Delete(_directory, recursive: true);
    }

    private static string Root()
    {
        DirectoryInfo? directory = new(AppContext.BaseDirectory);
        while (directory is not null && !File.Exists(Path.Combine(directory.FullName, "docs", "skins.md")))
            directory = directory.Parent;
        Assert.NotNull(directory);
        return directory.FullName;
    }
}
