// Generated by tools/omarchy-skins.py. Do not edit.
var palettes = {
  "catppuccin": {
    "fill": "#a6e3a1",
    "warning": "#f9e2af",
    "hot": "#f38ba8",
    "track": "#161622",
    "warningLevel": 0.7,
    "hotLevel": 0.9
  },
  "catppuccin-latte": {
    "fill": "#2b6d1d",
    "warning": "#875612",
    "hot": "#d20f39",
    "track": "#ccd0da",
    "warningLevel": 0.7,
    "hotLevel": 0.9
  },
  "everforest": {
    "fill": "#a7c080",
    "warning": "#dbbc7f",
    "hot": "#e67e80",
    "track": "#181d20",
    "warningLevel": 0.7,
    "hotLevel": 0.9
  },
  "gruvbox": {
    "fill": "#a9b665",
    "warning": "#d8a657",
    "hot": "#ea6962",
    "track": "#161616",
    "warningLevel": 0.7,
    "hotLevel": 0.9
  },
  "kanagawa": {
    "fill": "#98bb6c",
    "warning": "#e6c384",
    "hot": "#c34043",
    "track": "#111116",
    "warningLevel": 0.7,
    "hotLevel": 0.9
  },
  "matte-black": {
    "fill": "#bebebe",
    "warning": "#e68e0d",
    "hot": "#d35f5f",
    "track": "#090909",
    "warningLevel": 0.7,
    "hotLevel": 0.9
  },
  "nord": {
    "fill": "#a3be8c",
    "warning": "#ebcb8b",
    "hot": "#d47f89",
    "track": "#191c23",
    "warningLevel": 0.7,
    "hotLevel": 0.9
  },
  "opendeck": {
    "fill": "#2ecc71",
    "warning": "#f2c14e",
    "hot": "#ff4b4b",
    "track": "#0d0d0d",
    "warningLevel": 0.7,
    "hotLevel": 0.9
  },
  "osaka-jade": {
    "fill": "#549E6A",
    "warning": "#E5C736",
    "hot": "#FF5345",
    "track": "#090F0D",
    "warningLevel": 0.7,
    "hotLevel": 0.9
  },
  "ristretto": {
    "fill": "#adda78",
    "warning": "#f9cc6c",
    "hot": "#fd6883",
    "track": "#181414",
    "warningLevel": 0.7,
    "hotLevel": 0.9
  },
  "rose-pine": {
    "fill": "#286983",
    "warning": "#a66711",
    "hot": "#8a4257",
    "track": "#e1dbd5",
    "warningLevel": 0.7,
    "hotLevel": 0.9
  },
  "tokyo-night": {
    "fill": "#9ece6a",
    "warning": "#e0af68",
    "hot": "#f7768e",
    "track": "#13141c",
    "warningLevel": 0.7,
    "hotLevel": 0.9
  }
};
