#!/usr/bin/env python3
# Writes icon.h: the OpenXLR icon as _NET_WM_ICON data, for the editor window.
# Run it again when src/OpenXLR.UI/Assets/icon-*.png change.
import os
from PIL import Image

here = os.path.dirname(os.path.abspath(__file__))
assets = os.path.join(here, "..", "src", "OpenXLR.UI", "Assets")
words = []
for size in (32, 48, 64):
    image = Image.open(os.path.join(assets, f"icon-{size}.png")).convert("RGBA")
    assert image.size == (size, size)
    words += [size, size]
    pixels = image.tobytes()
    for i in range(0, len(pixels), 4):
        r, g, b, a = pixels[i:i + 4]
        words.append((a << 24) | (r << 16) | (g << 8) | b)
with open(os.path.join(here, "icon.h"), "w") as out:
    out.write("// SPDX-License-Identifier: GPL-3.0-only\n")
    out.write("// Generated by make-icon.py from src/OpenXLR.UI/Assets: the OpenXLR icon\n")
    out.write("// at 32, 48 and 64 pixels as _NET_WM_ICON data. Do not edit.\n")
    out.write("#pragma once\n\n")
    out.write(f"static const unsigned long openxlr_icon_length = {len(words)};\n")
    out.write("static const unsigned long openxlr_icon[] = {\n")
    for i in range(0, len(words), 8):
        out.write("  " + ", ".join(f"0x{w:08x}" for w in words[i:i + 8]) + ",\n")
    out.write("};\n")
