#!/usr/bin/env python3
"""Export the embedded skins' meter tokens for the Omarchy QML client."""
import argparse
import json
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "packaging/omarchy/openxlr.mixer/Skins.js"
HEADER = "// Generated by tools/omarchy-skins.py. Do not edit.\nvar palettes = "
TOKENS = {"fill": "Fill", "warning": "Warning", "hot": "Hot", "track": "Track",
          "warningLevel": "WarningLevel", "hotLevel": "HotLevel"}
# SkinTokens supplies these when a skin leaves a threshold unset. The .NET
# drift test regenerates with SkinTokens.Find so changes there are caught too.
DEFAULTS = {"WarningLevel": 0.7, "HotLevel": 0.9}


def generate():
    palettes = {}
    for path in sorted((ROOT / "src/OpenXLR.UI/Assets/Skins").glob("*/skin.json")):
        document = json.loads(path.read_text())
        skin_id = path.parent.name
        if document["id"] != skin_id:
            raise ValueError(f"{path}: skin id differs from its directory")
        tokens = document["tokens"]
        palette = {}
        for key, token in TOKENS.items():
            value = tokens.get("Ox.Meter." + token, DEFAULTS.get(token))
            if token in DEFAULTS:
                if type(value) not in (int, float) or not 0 <= value <= 1:
                    raise ValueError(f"{path}: invalid meter threshold {token}")
            elif not isinstance(value, str) or not re.fullmatch(r"#[0-9a-fA-F]{6}", value):
                raise ValueError(f"{path}: {token} must be a flat RGB colour")
            palette[key] = value
        if palette["warningLevel"] > palette["hotLevel"]:
            raise ValueError(f"{path}: meter thresholds cross")
        palettes[skin_id] = palette
    if not palettes:
        raise ValueError("No embedded skins found")
    return HEADER + json.dumps(palettes, indent=2, ensure_ascii=False) + ";\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true", help="fail if Skins.js differs")
    mode.add_argument("--stdout", action="store_true", help="generate without writing a file")
    args = parser.parse_args()
    generated = generate()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != generated:
            sys.exit("Skins.js is out of date; run python3 tools/omarchy-skins.py")
        print("Omarchy skins: generated table matches the embedded skin files")
    elif args.stdout:
        sys.stdout.write(generated)
    else:
        OUTPUT.write_text(generated)
        print(f"Wrote {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
